version: "3"
services:
  front:
    image : httpd
    ports:
      - "6980:80"
    volumes:
        - ./front:/usr/local/apache2/htdocs

  mariadb.ccd:
    image: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"

  api:
    image: "node:alpine"
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb.ccd